using System.Globalization;
using System.Resources;

namespace DriverGuardian.UI.Wpf.Localization;

public static class Resources
{
    private static readonly ResourceManager ResourceManager = new("DriverGuardian.UI.Wpf.Localization.Resources", typeof(Resources).Assembly);

    public static string MainWindow_Title => GetString(nameof(MainWindow_Title));
    public static string Status_Initial => GetString(nameof(Status_Initial));
    public static string Status_Ready => GetString(nameof(Status_Ready));
    public static string Status_Scanning => GetString(nameof(Status_Scanning));
    public static string Status_Scan_Completed_Ready => GetString(nameof(Status_Scan_Completed_Ready));
    public static string Status_Scan_Completed_No_Action => GetString(nameof(Status_Scan_Completed_No_Action));
    public static string Scan_Action => GetString(nameof(Scan_Action));
    public static string Scan_Summary_Format => GetString(nameof(Scan_Summary_Format));
    public static string Discovery_Inspection_Summary_Format => GetString(nameof(Discovery_Inspection_Summary_Format));
    public static string Recommendation_Summary_Format => GetString(nameof(Recommendation_Summary_Format));
    public static string Manual_Handoff_Summary_Format => GetString(nameof(Manual_Handoff_Summary_Format));
    public static string Verification_Summary_Format => GetString(nameof(Verification_Summary_Format));
    public static string Action_Flow_Title => GetString(nameof(Action_Flow_Title));
    public static string Scan_Overview_Title => GetString(nameof(Scan_Overview_Title));
    public static string Scan_Overview_Empty_State => GetString(nameof(Scan_Overview_Empty_State));
    public static string Action_Flow_Safety_Notice => GetString(nameof(Action_Flow_Safety_Notice));
    public static string Action_Status_Required => GetString(nameof(Action_Status_Required));
    public static string Action_Status_Available => GetString(nameof(Action_Status_Available));
    public static string Action_Status_Blocked => GetString(nameof(Action_Status_Blocked));
    public static string Action_Status_Wait => GetString(nameof(Action_Status_Wait));
    public static string Action_Status_Not_Available => GetString(nameof(Action_Status_Not_Available));
    public static string Action_Status_Return => GetString(nameof(Action_Status_Return));
    public static string Action_Step_Review_Recommendation => GetString(nameof(Action_Step_Review_Recommendation));
    public static string Action_Step_Review_Recommendation_Hint => GetString(nameof(Action_Step_Review_Recommendation_Hint));
    public static string Action_Step_Open_Official_Source => GetString(nameof(Action_Step_Open_Official_Source));
    public static string Action_Step_Open_Official_Source_Hint => GetString(nameof(Action_Step_Open_Official_Source_Hint));
    public static string Action_Step_Download_Manually => GetString(nameof(Action_Step_Download_Manually));
    public static string Action_Step_Download_Manually_Hint => GetString(nameof(Action_Step_Download_Manually_Hint));
    public static string Action_Step_Install_Outside_App => GetString(nameof(Action_Step_Install_Outside_App));
    public static string Action_Step_Install_Outside_App_Hint => GetString(nameof(Action_Step_Install_Outside_App_Hint));
    public static string Action_Step_Return_For_Verification => GetString(nameof(Action_Step_Return_For_Verification));
    public static string Action_Step_Return_For_Verification_Hint => GetString(nameof(Action_Step_Return_For_Verification_Hint));

    public static string Workflow_Headline_Empty => GetString(nameof(Workflow_Headline_Empty));
    public static string Workflow_Hint_Empty => GetString(nameof(Workflow_Hint_Empty));
    public static string Workflow_Headline_Ready => GetString(nameof(Workflow_Headline_Ready));
    public static string Workflow_Hint_Ready => GetString(nameof(Workflow_Hint_Ready));
    public static string Workflow_Headline_No_Recommendation => GetString(nameof(Workflow_Headline_No_Recommendation));
    public static string Workflow_Hint_No_Recommendation => GetString(nameof(Workflow_Hint_No_Recommendation));
    public static string Workflow_Headline_Official_Source_Limited => GetString(nameof(Workflow_Headline_Official_Source_Limited));
    public static string Workflow_Hint_Official_Source_Limited => GetString(nameof(Workflow_Hint_Official_Source_Limited));
    public static string Workflow_Headline_Manual_Action_Limited => GetString(nameof(Workflow_Headline_Manual_Action_Limited));
    public static string Workflow_Hint_Manual_Action_Limited => GetString(nameof(Workflow_Hint_Manual_Action_Limited));
    public static string Recommendation_Section_Title => GetString(nameof(Recommendation_Section_Title));
    public static string Recommendation_Section_Hint => GetString(nameof(Recommendation_Section_Hint));
    public static string Recommendation_Secondary_Summary_Format => GetString(nameof(Recommendation_Secondary_Summary_Format));
    public static string Recommendation_Primary_Summary_Format => GetString(nameof(Recommendation_Primary_Summary_Format));
    public static string Recommendation_Secondary_Toggle_Format => GetString(nameof(Recommendation_Secondary_Toggle_Format));
    public static string Recommendation_Secondary_Hide => GetString(nameof(Recommendation_Secondary_Hide));
    public static string Recommendation_Empty_State_Pre_Scan => GetString(nameof(Recommendation_Empty_State_Pre_Scan));
    public static string Recommendation_Empty_State_No_Action => GetString(nameof(Recommendation_Empty_State_No_Action));
    public static string Recommendation_Empty_State => GetString(nameof(Recommendation_Empty_State));
    public static string Recommendation_State_Ready_For_Manual_Action => GetString(nameof(Recommendation_State_Ready_For_Manual_Action));
    public static string Recommendation_State_Ready_For_Manual_Action_Hint => GetString(nameof(Recommendation_State_Ready_For_Manual_Action_Hint));
    public static string Recommendation_State_Insufficient_Evidence => GetString(nameof(Recommendation_State_Insufficient_Evidence));
    public static string Recommendation_State_Insufficient_Evidence_Hint => GetString(nameof(Recommendation_State_Insufficient_Evidence_Hint));
    public static string Recommendation_State_Blocked => GetString(nameof(Recommendation_State_Blocked));
    public static string Recommendation_State_Blocked_Hint => GetString(nameof(Recommendation_State_Blocked_Hint));
    public static string Manual_Section_Title => GetString(nameof(Manual_Section_Title));
    public static string Manual_Section_Hint => GetString(nameof(Manual_Section_Hint));
    public static string Manual_Section_Empty_State => GetString(nameof(Manual_Section_Empty_State));
    public static string Verification_Section_Title => GetString(nameof(Verification_Section_Title));
    public static string Verification_Section_Hint => GetString(nameof(Verification_Section_Hint));
    public static string Verification_Rescan_Hint => GetString(nameof(Verification_Rescan_Hint));
    public static string Verification_Rescan_Hint_No_Action => GetString(nameof(Verification_Rescan_Hint_No_Action));
    public static string Verification_Section_Empty_State_Pre_Scan => GetString(nameof(Verification_Section_Empty_State_Pre_Scan));
    public static string Verification_Section_Empty_State_No_Action => GetString(nameof(Verification_Section_Empty_State_No_Action));

    public static string Official_Source_Summary_Ready_Format => GetString(nameof(Official_Source_Summary_Ready_Format));
    public static string Official_Source_Summary_Direct_Driver_Page_Format => GetString(nameof(Official_Source_Summary_Direct_Driver_Page_Format));
    public static string Official_Source_Summary_Vendor_Support_Page_Format => GetString(nameof(Official_Source_Summary_Vendor_Support_Page_Format));
    public static string Official_Source_Summary_Insufficient_Evidence => GetString(nameof(Official_Source_Summary_Insufficient_Evidence));
    public static string Official_Source_Summary_Blocked_Format => GetString(nameof(Official_Source_Summary_Blocked_Format));
    public static string Official_Source_Blocked_No_Reason => GetString(nameof(Official_Source_Blocked_No_Reason));
    public static string Official_Source_Url_Unavailable => GetString(nameof(Official_Source_Url_Unavailable));
    public static string Recommendation_Device_Format => GetString(nameof(Recommendation_Device_Format));
    public static string Recommendation_Technical_Id_Format => GetString(nameof(Recommendation_Technical_Id_Format));
    public static string Recommendation_Device_Generic => GetString(nameof(Recommendation_Device_Generic));
    public static string Recommendation_Device_Unknown => GetString(nameof(Recommendation_Device_Unknown));
    public static string Recommendation_Manual_Handoff_Format => GetString(nameof(Recommendation_Manual_Handoff_Format));
    public static string Recommendation_Manual_Action_Format => GetString(nameof(Recommendation_Manual_Action_Format));
    public static string Recommendation_Verification_Format => GetString(nameof(Recommendation_Verification_Format));
    public static string Recommendation_Verification_Status_Format => GetString(nameof(Recommendation_Verification_Status_Format));
    public static string Recommendation_Title_Recommended => GetString(nameof(Recommendation_Title_Recommended));
    public static string Recommendation_Title_Not_Recommended => GetString(nameof(Recommendation_Title_Not_Recommended));
    public static string Recommendation_Candidate_Version_Format => GetString(nameof(Recommendation_Candidate_Version_Format));
    public static string Recommendation_Candidate_Unavailable => GetString(nameof(Recommendation_Candidate_Unavailable));
    public static string Recommendation_Reason_Unavailable => GetString(nameof(Recommendation_Reason_Unavailable));
    public static string Recommendation_Next_Step_Recommended => GetString(nameof(Recommendation_Next_Step_Recommended));
    public static string Recommendation_Next_Step_Deferred => GetString(nameof(Recommendation_Next_Step_Deferred));
    public static string Recommendation_Installed_Driver_Format => GetString(nameof(Recommendation_Installed_Driver_Format));
    public static string Recommendation_Provider_Unknown => GetString(nameof(Recommendation_Provider_Unknown));
    public static string Preview_Window_Title => GetString(nameof(Preview_Window_Title));
    public static string Preview_Mode_Section_Title => GetString(nameof(Preview_Mode_Section_Title));
    public static string Preview_Mode_Banner => GetString(nameof(Preview_Mode_Banner));
    public static string Preview_Mode_Scenario_Label => GetString(nameof(Preview_Mode_Scenario_Label));
    public static string Preview_Apply_Scenario_Action => GetString(nameof(Preview_Apply_Scenario_Action));
    public static string Preview_Mode_Status_Format => GetString(nameof(Preview_Mode_Status_Format));
    public static string Preview_Scenario_First_Run => GetString(nameof(Preview_Scenario_First_Run));
    public static string Preview_Scenario_No_Action => GetString(nameof(Preview_Scenario_No_Action));
    public static string Preview_Scenario_Limited_Evidence => GetString(nameof(Preview_Scenario_Limited_Evidence));
    public static string Preview_Scenario_Manual_Ready => GetString(nameof(Preview_Scenario_Manual_Ready));
    public static string Preview_Scenario_Verification_Return => GetString(nameof(Preview_Scenario_Verification_Return));
    public static string Preview_Scenario_History_Export => GetString(nameof(Preview_Scenario_History_Export));
    public static string Settings_Title => GetString(nameof(Settings_Title));
    public static string Settings_History_Retention_Label => GetString(nameof(Settings_History_Retention_Label));
    public static string Settings_Report_Format_Label => GetString(nameof(Settings_Report_Format_Label));
    public static string Settings_Report_Format_Markdown => GetString(nameof(Settings_Report_Format_Markdown));
    public static string Settings_Report_Format_PlainText => GetString(nameof(Settings_Report_Format_PlainText));
    public static string Settings_Verification_Hint_Label => GetString(nameof(Settings_Verification_Hint_Label));
    public static string Settings_Diagnostic_Logging_Label => GetString(nameof(Settings_Diagnostic_Logging_Label));
    public static string Settings_Diagnostic_Custom_Log_Folder_Label => GetString(nameof(Settings_Diagnostic_Custom_Log_Folder_Label));
    public static string Settings_Diagnostic_Effective_Log_Folder_Label => GetString(nameof(Settings_Diagnostic_Effective_Log_Folder_Label));
    public static string Settings_Open_Logs_Folder_Action => GetString(nameof(Settings_Open_Logs_Folder_Action));
    public static string Settings_Logs_Folder_Open_Failed => GetString(nameof(Settings_Logs_Folder_Open_Failed));
    public static string Settings_Save_Action => GetString(nameof(Settings_Save_Action));
    public static string Settings_Loaded => GetString(nameof(Settings_Loaded));
    public static string Settings_Saved => GetString(nameof(Settings_Saved));
    public static string Settings_Load_Error => GetString(nameof(Settings_Load_Error));
    public static string Report_Export_Title => GetString(nameof(Report_Export_Title));
    public static string Report_Export_Hint => GetString(nameof(Report_Export_Hint));
    public static string Report_Export_Action => GetString(nameof(Report_Export_Action));
    public static string Report_Export_Status_No_Data => GetString(nameof(Report_Export_Status_No_Data));
    public static string Report_Export_Status_Ready => GetString(nameof(Report_Export_Status_Ready));
    public static string Report_Export_Status_Saved => GetString(nameof(Report_Export_Status_Saved));
    public static string Report_Export_Status_Canceled => GetString(nameof(Report_Export_Status_Canceled));
    public static string Report_Export_Status_Save_Failed => GetString(nameof(Report_Export_Status_Save_Failed));
    public static string Report_Export_Markdown_Filter => GetString(nameof(Report_Export_Markdown_Filter));
    public static string Report_Export_Text_Filter => GetString(nameof(Report_Export_Text_Filter));

    public static string Recent_History_Section_Title => GetString(nameof(Recent_History_Section_Title));
    public static string Recent_History_Section_Hint => GetString(nameof(Recent_History_Section_Hint));
    public static string Recent_History_Empty_State => GetString(nameof(Recent_History_Empty_State));
    public static string Recent_History_Type_Scan => GetString(nameof(Recent_History_Type_Scan));
    public static string Recent_History_Type_Recommendation => GetString(nameof(Recent_History_Type_Recommendation));
    public static string Recent_History_Type_Verification => GetString(nameof(Recent_History_Type_Verification));
    public static string Recent_History_Type_Unknown => GetString(nameof(Recent_History_Type_Unknown));
    public static string Recent_History_Scan_Summary_Format => GetString(nameof(Recent_History_Scan_Summary_Format));
    public static string Recent_History_Scan_Status_Format => GetString(nameof(Recent_History_Scan_Status_Format));
    public static string Recent_History_Recommendation_Summary => GetString(nameof(Recent_History_Recommendation_Summary));
    public static string Recent_History_Recommendation_Status_Format => GetString(nameof(Recent_History_Recommendation_Status_Format));
    public static string Recent_History_Verification_Summary => GetString(nameof(Recent_History_Verification_Summary));
    public static string Recent_History_Verification_Status_Format => GetString(nameof(Recent_History_Verification_Status_Format));
    public static string Recent_History_Verification_Status_Passed => GetString(nameof(Recent_History_Verification_Status_Passed));
    public static string Recent_History_Verification_Status_Failed => GetString(nameof(Recent_History_Verification_Status_Failed));
    public static string Recent_History_Verification_Status_Skipped => GetString(nameof(Recent_History_Verification_Status_Skipped));
    public static string Recent_History_Verification_Status_Unknown => GetString(nameof(Recent_History_Verification_Status_Unknown));
    public static string Recent_History_Verification_Note_Empty => GetString(nameof(Recent_History_Verification_Note_Empty));
    public static string Recent_History_Unknown_Summary => GetString(nameof(Recent_History_Unknown_Summary));
    public static string Recent_History_Unknown_Status => GetString(nameof(Recent_History_Unknown_Status));
    public static string Recent_History_Scan_Guidance => GetString(nameof(Recent_History_Scan_Guidance));
    public static string Recent_History_Recommendation_Guidance => GetString(nameof(Recent_History_Recommendation_Guidance));
    public static string Recent_History_Verification_Guidance => GetString(nameof(Recent_History_Verification_Guidance));
    public static string Recent_History_Unknown_Guidance => GetString(nameof(Recent_History_Unknown_Guidance));

    private static string GetString(string key)
    {
        return ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
    }
}
