namespace DriverGuardian.UI.Wpf.Localization;

public static class UiStrings
{
    public static string MainWindowTitle => Resources.MainWindow_Title;
    public static string StatusReady => Resources.Status_Ready;
    public static string StatusScanning => Resources.Status_Scanning;
    public static string ScanAction => Resources.Scan_Action;
    public static string ScanSummaryFormat => Resources.Scan_Summary_Format;
    public static string DiscoveryInspectionSummaryFormat => Resources.Discovery_Inspection_Summary_Format;
    public static string RecommendationSummaryFormat => Resources.Recommendation_Summary_Format;
    public static string ManualHandoffSummaryFormat => Resources.Manual_Handoff_Summary_Format;
    public static string VerificationSummaryFormat => Resources.Verification_Summary_Format;
    public static string ActionFlowTitle => Resources.Action_Flow_Title;
    public static string ActionFlowSafetyNotice => Resources.Action_Flow_Safety_Notice;
    public static string ActionStatusRequired => Resources.Action_Status_Required;
    public static string ActionStatusAvailable => Resources.Action_Status_Available;
    public static string ActionStatusBlocked => Resources.Action_Status_Blocked;
    public static string ActionStatusWait => Resources.Action_Status_Wait;
    public static string ActionStatusNotAvailable => Resources.Action_Status_Not_Available;
    public static string ActionStatusReturn => Resources.Action_Status_Return;
    public static string ActionStepReviewRecommendation => Resources.Action_Step_Review_Recommendation;
    public static string ActionStepReviewRecommendationHint => Resources.Action_Step_Review_Recommendation_Hint;
    public static string ActionStepOpenOfficialSource => Resources.Action_Step_Open_Official_Source;
    public static string ActionStepOpenOfficialSourceHint => Resources.Action_Step_Open_Official_Source_Hint;
    public static string ActionStepDownloadManually => Resources.Action_Step_Download_Manually;
    public static string ActionStepDownloadManuallyHint => Resources.Action_Step_Download_Manually_Hint;
    public static string ActionStepInstallOutsideApp => Resources.Action_Step_Install_Outside_App;
    public static string ActionStepInstallOutsideAppHint => Resources.Action_Step_Install_Outside_App_Hint;
    public static string ActionStepReturnForVerification => Resources.Action_Step_Return_For_Verification;
    public static string ActionStepReturnForVerificationHint => Resources.Action_Step_Return_For_Verification_Hint;

    public static string OfficialSourceSummaryReadyFormat => Resources.Official_Source_Summary_Ready_Format;
    public static string OfficialSourceSummaryBlockedFormat => Resources.Official_Source_Summary_Blocked_Format;
    public static string OfficialSourceBlockedNoReason => Resources.Official_Source_Blocked_No_Reason;
    public static string OfficialSourceUrlUnavailable => Resources.Official_Source_Url_Unavailable;
    public static string RecommendationDeviceFormat => Resources.Recommendation_Device_Format;
    public static string RecommendationManualHandoffFormat => Resources.Recommendation_Manual_Handoff_Format;
    public static string RecommendationManualActionFormat => Resources.Recommendation_Manual_Action_Format;
    public static string RecommendationVerificationFormat => Resources.Recommendation_Verification_Format;
    public static string RecommendationTitleRecommended => Resources.Recommendation_Title_Recommended;
    public static string RecommendationTitleNotRecommended => Resources.Recommendation_Title_Not_Recommended;
    public static string RecommendationCandidateVersionFormat => Resources.Recommendation_Candidate_Version_Format;
    public static string RecommendationCandidateUnavailable => Resources.Recommendation_Candidate_Unavailable;
    public static string RecommendationReasonUnavailable => Resources.Recommendation_Reason_Unavailable;
    public static string RecommendationNextStepRecommended => Resources.Recommendation_Next_Step_Recommended;
    public static string RecommendationNextStepDeferred => Resources.Recommendation_Next_Step_Deferred;
    public static string RecommendationInstalledDriverFormat => Resources.Recommendation_Installed_Driver_Format;
    public static string RecommendationProviderUnknown => Resources.Recommendation_Provider_Unknown;
    public static string SettingsTitle => Resources.Settings_Title;
    public static string SettingsHistoryRetentionLabel => Resources.Settings_History_Retention_Label;
    public static string SettingsReportFormatLabel => Resources.Settings_Report_Format_Label;
    public static string SettingsReportFormatMarkdown => Resources.Settings_Report_Format_Markdown;
    public static string SettingsReportFormatPlainText => Resources.Settings_Report_Format_PlainText;
    public static string SettingsVerificationHintLabel => Resources.Settings_Verification_Hint_Label;
    public static string SettingsSaveAction => Resources.Settings_Save_Action;
    public static string SettingsLoaded => Resources.Settings_Loaded;
    public static string SettingsSaved => Resources.Settings_Saved;
    public static string SettingsLoadError => Resources.Settings_Load_Error;
}
