// <auto-generated />
using System.Globalization;
using System.Resources;

namespace DriverGuardian.UI.Wpf.Resources;

public class Strings
{
    private static readonly ResourceManager ResourceManagerInstance = new("DriverGuardian.UI.Wpf.Resources.Strings", typeof(Strings).Assembly);

    public static ResourceManager ResourceManager => ResourceManagerInstance;

    public static CultureInfo? Culture { get; set; }
}
